import React from 'react';

// Using forwardRef so react-to-print can target it
const PDFLayout = React.forwardRef(({ scanData, excludedIds, logo }, ref) => {
    if (!scanData) return <div ref={ref} />;

    const validFindings = scanData.findings.filter(f => !excludedIds.includes(f.id + f.description)); // naive id generation

    // Filter findings: ID might not be unique if tool returns multiple same issues, so use index in real app or unique key
    // We'll pass filtered list directly from parent to be safer, but here we handled ID logic.
    // Actually, let's assume the parent passes `findings` prop already filtered.

    return (
        <div ref={ref} className="bg-white text-black p-10 min-h-screen print:p-0">
            {/* Header */}
            <div className="flex justify-between items-center border-b-2 border-slate-200 pb-4 mb-8">
                <div className="flex items-center space-x-4">
                    {logo ? (
                        <img src={logo} alt="Company Logo" className="h-16 object-contain" />
                    ) : (
                        <div className="text-2xl font-bold text-slate-800">Scanner Report</div>
                    )}
                </div>
                <div className="text-right">
                    <h1 className="text-3xl font-bold text-slate-900">Security Report</h1>
                    <p className="text-slate-500 text-sm">Target: {scanData.target}</p>
                    <p className="text-slate-500 text-sm">Date: {new Date().toLocaleDateString()}</p>
                </div>
            </div>

            {/* Summary */}
            <div className="mb-8 p-4 bg-slate-50 rounded-lg">
                <h2 className="text-xl font-bold mb-2 text-slate-800">Executive Summary</h2>
                <p className="text-slate-600">
                    A scan was performed on {scanData.target}. A total of {validFindings.length} issues were identified.
                    Please review the details below.
                </p>
            </div>

            {/* Findings */}
            <div className="space-y-6">
                {validFindings.map((finding, index) => (
                    <div key={index} className="border border-slate-200 rounded-lg p-4 break-inside-avoid">
                        <div className="flex justify-between items-start mb-2">
                            <h3 className="font-bold text-lg text-slate-900">{finding.name || finding.tool}</h3>
                            <span className={`px-3 py-1 rounded-full text-xs font-bold ${finding.severity === 'critical' || finding.severity === 'high' ? 'bg-red-100 text-red-800' :
                                finding.severity === 'medium' ? 'bg-orange-100 text-orange-800' :
                                    'bg-slate-100 text-slate-800'
                                }`}>
                                {finding.severity || 'INFO'}
                            </span>
                        </div>
                        <p className="text-slate-700 text-sm mb-2">{finding.description}</p>
                        {finding.tool && <p className="text-xs text-slate-400 uppercase">Values provided by: {finding.tool}</p>}
                    </div>
                ))}

                {validFindings.length === 0 && (
                    <p className="text-center text-slate-500 italic">No vulnerabilities found matching criteria.</p>
                )}
            </div>

            <div className="mt-12 pt-4 border-t border-slate-200 text-center text-slate-400 text-xs text-opacity-50">
                Generated by Antigravity Scanner
            </div>
        </div>
    );
});

export default PDFLayout;
